### PR TITLE
Added ability to have different types of constellations, like Norse

### PR DESCRIPTION
**Pull request by belaja-akacija**
I want to preface by saying that I'm not a C++ dev by no means (this was actually my first real foray into the language). 

I have added the ability to have different cultures' constellations included. The default is still to display the 88 modern constellations. 
If you run `starfetch -n norse friggerock` for example, it will access the new `norse-constellations` directory, instead of the main `constellations`.

This is by no means a finished rework of the functions, but it works and can be extended in the future to include more constellations.
For example, the switch statement under case `-n` should probably use a multidimensional array, plist, alist, or something of that sort to detect which directory to use, instead of writing an if else statement for every new directory addition. However, I do not know how to write that in C++, so hopefully that can be addressed by someone who knows more than me. 
Another thing that might be worth refactoring, is the RandomConstRefactor() function, which I rewrote to be able to include all the constellations in the randomizer. It seems a bit messy to me, due to all those for loops, but it functions.

You can refer to the Common Lisp file that I included, to get an idea what my implementation intended to add, since I am much more comfortable writing in Lisp. I've also added (hopefully) sufficient comments to my code additions.

I will try and add some more constellations to each directory, so there doesn't exist only one in `norse-constellations`. 

Let me know if I need to fix anything before merging anything. 

Hope this helps! 
-- Belaja-akacija

### CODE REVIEW

**Comment by Haruno19** [comment]
Thank you so much for working on starfetch! :)

That definitely is a nice idea for a feature, I like it, plus as you said it can also be expanded more and more in the future, which is something I'm very fond of! 

I did some testing too and it works flawlessly, I also like the way you designed the new feature (the separate folder for each culture, and the syntax as well, feels pretty robust). Also I gave a quick look at the code, thanks for all the comments and the Lisp file, thinking using different paradigms for the same problem really helps figuring out how to make stuff work or work better, so I truly appreciate it! 

I won't be able to look deeper into it until next week, but since everything already works fine, I'll merge the PR right away anyways :)

Thanks a lot for your work!

**Comment by Haruno19** [comment]
Next week I'll as well write down what you did and your name in the README file as I did for all the other contributors (I'm sorry I can't do it right away) and update the other paragraphs to match the new features. 
Then maybe after reviewing the code, and once some more norse constellation is added, I'll publish a new release!

**Comment by belaja-akacija** [comment]
Hi again!
I don't want to open another pull request, just seems unnecessary, since it's related to this one. 

I just want to give a little update to what I worked on. As mentioned above, the refactored randomising function was  a little weak. It also had the annoying bug of being biased and heavily favoured the first couple of entries in whichever directory it chose. (which is probably why it was about 2x faster than the original algorithm)

I did a bit of research and implemented reservoir sampling, so it doesn't have to know how many elements exist inside of the directory to choose a random sample. Now, it doesn't seem to be as biased.
It's not as fast as the biased one, but it's marginally faster than the original regardless (which is a bit silly, I know, to focus on, since it's not really that serious of a program. But I think it's fun :) ).

You can check out my fork of the refactors and I have also included some tests, in case you were curious.
Thanks again for such a fun little CLI program, it's a great addition to my zshrc!

-- Belaja-akacija


A not so scientific comparison of the original and refactored functions: [test-time.txt](https://github.com/Haruno19/starfetch/files/11992373/test-time.txt)

**Comment by Haruno19** [comment]
Hi! I'm deeply sorry it took me this long to reply.

I'm very very grateful for your work! 
I've read through the tests you've provided, both the results and the functions that were tested; I don't think it's silly at all to focus on execution times, even for a program like starfetch! :) I think it's fascinating 
I find the improvements you made to be very much valid, and I would gladly merge a PR if you feel like making another one in the future! 

I really can't thank you enough. I love it when people make efforts to work on something out of sheer passion and curiosity, that was one of the goals I had in mind for starfetch, so I am truly grateful for your contribution :)  
(and I'm even more glad that you had a fun time working on it!)

**Pull request merged**
